// Mock data for development
// This will be replaced with real API calls to C# backend

import { Product, Transaction, Alert, DashboardStats, MLPrediction } from '@/types';

export const mockProducts: Product[] = [
  {
    id: '1',
    sku: 'PRD-001',
    name: 'Laptop Dell XPS 15',
    category: 'Electronics',
    quantity: 45,
    minThreshold: 20,
    price: 1299.99,
    supplier: 'Dell Inc.',
    lastRestocked: '2024-01-15',
    status: 'in-stock',
  },
  {
    id: '2',
    sku: 'PRD-002',
    name: 'Office Chair Ergonomic',
    category: 'Furniture',
    quantity: 12,
    minThreshold: 15,
    price: 249.99,
    supplier: 'Office Supplies Co.',
    lastRestocked: '2024-01-10',
    status: 'low-stock',
  },
  {
    id: '3',
    sku: 'PRD-003',
    name: 'Wireless Mouse',
    category: 'Accessories',
    quantity: 0,
    minThreshold: 30,
    price: 29.99,
    supplier: 'Tech Accessories Ltd.',
    lastRestocked: '2023-12-20',
    status: 'out-of-stock',
  },
  {
    id: '4',
    sku: 'PRD-004',
    name: 'Monitor 27" 4K',
    category: 'Electronics',
    quantity: 28,
    minThreshold: 10,
    price: 449.99,
    supplier: 'LG Electronics',
    lastRestocked: '2024-01-18',
    status: 'in-stock',
  },
  {
    id: '5',
    sku: 'PRD-005',
    name: 'Mechanical Keyboard',
    category: 'Accessories',
    quantity: 8,
    minThreshold: 12,
    price: 129.99,
    supplier: 'Gaming Gear Inc.',
    lastRestocked: '2024-01-12',
    status: 'low-stock',
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    productId: '1',
    productName: 'Laptop Dell XPS 15',
    type: 'sale',
    quantity: 2,
    price: 1299.99,
    total: 2599.98,
    date: '2024-01-20T10:30:00',
    user: 'John Doe',
    notes: 'Corporate sale',
  },
  {
    id: '2',
    productId: '2',
    productName: 'Office Chair Ergonomic',
    type: 'purchase',
    quantity: 20,
    price: 180.00,
    total: 3600.00,
    date: '2024-01-19T14:15:00',
    user: 'Admin',
    notes: 'Restocking order',
  },
  {
    id: '3',
    productId: '4',
    productName: 'Monitor 27" 4K',
    type: 'sale',
    quantity: 3,
    price: 449.99,
    total: 1349.97,
    date: '2024-01-20T09:00:00',
    user: 'Jane Smith',
  },
];

export const mockAlerts: Alert[] = [
  {
    id: '1',
    productId: '3',
    productName: 'Wireless Mouse',
    type: 'out-of-stock',
    message: 'Product is out of stock and requires immediate restocking',
    currentQuantity: 0,
    threshold: 30,
    severity: 'high',
    createdAt: '2024-01-20T08:00:00',
    resolved: false,
  },
  {
    id: '2',
    productId: '2',
    productName: 'Office Chair Ergonomic',
    type: 'low-stock',
    message: 'Stock level below minimum threshold',
    currentQuantity: 12,
    threshold: 15,
    severity: 'medium',
    createdAt: '2024-01-20T09:30:00',
    resolved: false,
  },
  {
    id: '3',
    productId: '5',
    productName: 'Mechanical Keyboard',
    type: 'low-stock',
    message: 'Consider reordering soon',
    currentQuantity: 8,
    threshold: 12,
    severity: 'medium',
    createdAt: '2024-01-20T11:00:00',
    resolved: false,
  },
];

export const mockDashboardStats: DashboardStats = {
  totalProducts: 150,
  lowStockItems: 12,
  outOfStockItems: 3,
  totalValue: 245678.50,
  todayTransactions: 28,
  weeklyGrowth: 12.5,
};

export const mockMLPredictions: MLPrediction[] = [
  {
    productId: '1',
    productName: 'Laptop Dell XPS 15',
    predictedDemand: 25,
    currentStock: 45,
    recommendedReorder: 0,
    confidence: 0.92,
    trend: 'stable',
  },
  {
    productId: '3',
    productName: 'Wireless Mouse',
    predictedDemand: 45,
    currentStock: 0,
    recommendedReorder: 60,
    confidence: 0.88,
    trend: 'increasing',
  },
  {
    productId: '5',
    productName: 'Mechanical Keyboard',
    predictedDemand: 18,
    currentStock: 8,
    recommendedReorder: 25,
    confidence: 0.85,
    trend: 'increasing',
  },
];
