// Mock data for development
// This will be replaced with real API calls to C# backend

import { Product, Transaction, Alert, DashboardStats, MLPrediction, Supplier, AuditLog } from '@/types';

export const mockProducts: Product[] = [
  {
    id: '1',
    sku: 'PRD-001',
    name: 'Laptop Dell XPS 15',
    category: 'Electronics',
    quantity: 45,
    minThreshold: 20,
    price: 1299.99,
    supplier: 'Dell Inc.',
    lastRestocked: '2024-01-15',
    status: 'in-stock',
    image: '💻',
  },
  {
    id: '2',
    sku: 'PRD-002',
    name: 'Office Chair Ergonomic',
    category: 'Furniture',
    quantity: 12,
    minThreshold: 15,
    price: 249.99,
    supplier: 'Office Supplies Co.',
    lastRestocked: '2024-01-10',
    status: 'low-stock',
    image: '🪑',
  },
  {
    id: '3',
    sku: 'PRD-003',
    name: 'Wireless Mouse Logitech',
    category: 'Accessories',
    quantity: 0,
    minThreshold: 30,
    price: 29.99,
    supplier: 'Tech Accessories Ltd.',
    lastRestocked: '2023-12-20',
    status: 'out-of-stock',
    image: '🖱️',
  },
  {
    id: '4',
    sku: 'PRD-004',
    name: 'Monitor 27" 4K LG',
    category: 'Electronics',
    quantity: 28,
    minThreshold: 10,
    price: 449.99,
    supplier: 'LG Electronics',
    lastRestocked: '2024-01-18',
    status: 'in-stock',
    image: '🖥️',
  },
  {
    id: '5',
    sku: 'PRD-005',
    name: 'Mechanical Keyboard RGB',
    category: 'Accessories',
    quantity: 8,
    minThreshold: 12,
    price: 129.99,
    supplier: 'Gaming Gear Inc.',
    lastRestocked: '2024-01-12',
    status: 'low-stock',
    image: '⌨️',
  },
  {
    id: '6',
    sku: 'PRD-006',
    name: 'Standing Desk Electric',
    category: 'Furniture',
    quantity: 35,
    minThreshold: 8,
    price: 599.99,
    supplier: 'Office Supplies Co.',
    lastRestocked: '2024-01-14',
    status: 'in-stock',
    image: '🏢',
  },
  {
    id: '7',
    sku: 'PRD-007',
    name: 'Webcam HD 1080p',
    category: 'Electronics',
    quantity: 52,
    minThreshold: 15,
    price: 79.99,
    supplier: 'Tech Accessories Ltd.',
    lastRestocked: '2024-01-16',
    status: 'in-stock',
    image: '📷',
  },
  {
    id: '8',
    sku: 'PRD-008',
    name: 'USB-C Hub 7-in-1',
    category: 'Accessories',
    quantity: 4,
    minThreshold: 20,
    price: 49.99,
    supplier: 'Tech Accessories Ltd.',
    lastRestocked: '2024-01-05',
    status: 'low-stock',
    image: '🔌',
  },
  {
    id: '9',
    sku: 'PRD-009',
    name: 'Noise Cancelling Headphones',
    category: 'Electronics',
    quantity: 18,
    minThreshold: 10,
    price: 299.99,
    supplier: 'Sony Corp.',
    lastRestocked: '2024-01-17',
    status: 'in-stock',
    image: '🎧',
  },
  {
    id: '10',
    sku: 'PRD-010',
    name: 'Printer LaserJet Pro',
    category: 'Electronics',
    quantity: 0,
    minThreshold: 5,
    price: 349.99,
    supplier: 'HP Inc.',
    lastRestocked: '2023-12-28',
    status: 'out-of-stock',
    image: '🖨️',
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    productId: '1',
    productName: 'Laptop Dell XPS 15',
    type: 'sale',
    quantity: 2,
    price: 1299.99,
    total: 2599.98,
    date: '2024-01-20T10:30:00',
    user: 'John Doe',
    notes: 'Corporate sale - Acme Corp',
  },
  {
    id: '2',
    productId: '2',
    productName: 'Office Chair Ergonomic',
    type: 'purchase',
    quantity: 20,
    price: 180.00,
    total: 3600.00,
    date: '2024-01-19T14:15:00',
    user: 'Admin',
    notes: 'Restocking order from supplier',
  },
  {
    id: '3',
    productId: '4',
    productName: 'Monitor 27" 4K LG',
    type: 'sale',
    quantity: 3,
    price: 449.99,
    total: 1349.97,
    date: '2024-01-20T09:00:00',
    user: 'Jane Smith',
  },
  {
    id: '4',
    productId: '5',
    productName: 'Mechanical Keyboard RGB',
    type: 'sale',
    quantity: 4,
    price: 129.99,
    total: 519.96,
    date: '2024-01-19T16:45:00',
    user: 'John Doe',
    notes: 'Gaming department order',
  },
  {
    id: '5',
    productId: '7',
    productName: 'Webcam HD 1080p',
    type: 'purchase',
    quantity: 30,
    price: 55.00,
    total: 1650.00,
    date: '2024-01-18T11:00:00',
    user: 'Admin',
    notes: 'Bulk purchase for remote teams',
  },
  {
    id: '6',
    productId: '9',
    productName: 'Noise Cancelling Headphones',
    type: 'sale',
    quantity: 5,
    price: 299.99,
    total: 1499.95,
    date: '2024-01-18T15:30:00',
    user: 'Jane Smith',
  },
  {
    id: '7',
    productId: '1',
    productName: 'Laptop Dell XPS 15',
    type: 'adjustment',
    quantity: -3,
    price: 1299.99,
    total: 0,
    date: '2024-01-17T09:00:00',
    user: 'Admin',
    notes: 'Damaged units removed from inventory',
  },
  {
    id: '8',
    productId: '6',
    productName: 'Standing Desk Electric',
    type: 'sale',
    quantity: 2,
    price: 599.99,
    total: 1199.98,
    date: '2024-01-17T14:20:00',
    user: 'John Doe',
  },
];

export const mockAlerts: Alert[] = [
  {
    id: '1',
    productId: '3',
    productName: 'Wireless Mouse Logitech',
    type: 'out-of-stock',
    message: 'Product is out of stock and requires immediate restocking',
    currentQuantity: 0,
    threshold: 30,
    severity: 'high',
    createdAt: '2024-01-20T08:00:00',
    resolved: false,
  },
  {
    id: '2',
    productId: '2',
    productName: 'Office Chair Ergonomic',
    type: 'low-stock',
    message: 'Stock level below minimum threshold',
    currentQuantity: 12,
    threshold: 15,
    severity: 'medium',
    createdAt: '2024-01-20T09:30:00',
    resolved: false,
  },
  {
    id: '3',
    productId: '5',
    productName: 'Mechanical Keyboard RGB',
    type: 'low-stock',
    message: 'Consider reordering soon',
    currentQuantity: 8,
    threshold: 12,
    severity: 'medium',
    createdAt: '2024-01-20T11:00:00',
    resolved: false,
  },
  {
    id: '4',
    productId: '10',
    productName: 'Printer LaserJet Pro',
    type: 'out-of-stock',
    message: 'Product out of stock — customer orders pending',
    currentQuantity: 0,
    threshold: 5,
    severity: 'high',
    createdAt: '2024-01-20T07:00:00',
    resolved: false,
  },
  {
    id: '5',
    productId: '8',
    productName: 'USB-C Hub 7-in-1',
    type: 'low-stock',
    message: 'Only 4 units remaining, reorder recommended',
    currentQuantity: 4,
    threshold: 20,
    severity: 'high',
    createdAt: '2024-01-20T10:00:00',
    resolved: false,
  },
];

export const mockDashboardStats: DashboardStats = {
  totalProducts: 150,
  lowStockItems: 12,
  outOfStockItems: 3,
  totalValue: 245678.50,
  todayTransactions: 28,
  weeklyGrowth: 12.5,
};

export const mockMLPredictions: MLPrediction[] = [
  {
    productId: '1',
    productName: 'Laptop Dell XPS 15',
    predictedDemand: 25,
    currentStock: 45,
    recommendedReorder: 0,
    confidence: 0.92,
    trend: 'stable',
  },
  {
    productId: '3',
    productName: 'Wireless Mouse Logitech',
    predictedDemand: 45,
    currentStock: 0,
    recommendedReorder: 60,
    confidence: 0.88,
    trend: 'increasing',
  },
  {
    productId: '5',
    productName: 'Mechanical Keyboard RGB',
    predictedDemand: 18,
    currentStock: 8,
    recommendedReorder: 25,
    confidence: 0.85,
    trend: 'increasing',
  },
  {
    productId: '4',
    productName: 'Monitor 27" 4K LG',
    predictedDemand: 15,
    currentStock: 28,
    recommendedReorder: 0,
    confidence: 0.91,
    trend: 'stable',
  },
  {
    productId: '9',
    productName: 'Noise Cancelling Headphones',
    predictedDemand: 22,
    currentStock: 18,
    recommendedReorder: 15,
    confidence: 0.87,
    trend: 'increasing',
  },
  {
    productId: '10',
    productName: 'Printer LaserJet Pro',
    predictedDemand: 8,
    currentStock: 0,
    recommendedReorder: 20,
    confidence: 0.79,
    trend: 'decreasing',
  },
];

export const mockSuppliers: Supplier[] = [
  {
    id: '1',
    name: 'Dell Inc.',
    contactPerson: 'Michael Chen',
    email: 'michael.chen@dell.com',
    phone: '+1 (512) 728-7800',
    address: 'Round Rock, TX, USA',
    productsSupplied: 2,
    totalOrders: 24,
    rating: 4.8,
    status: 'active',
  },
  {
    id: '2',
    name: 'Office Supplies Co.',
    contactPerson: 'Sarah Johnson',
    email: 'sarah@officesupplies.com',
    phone: '+1 (415) 555-0123',
    address: 'San Francisco, CA, USA',
    productsSupplied: 3,
    totalOrders: 18,
    rating: 4.5,
    status: 'active',
  },
  {
    id: '3',
    name: 'Tech Accessories Ltd.',
    contactPerson: 'James Wilson',
    email: 'james@techacc.com',
    phone: '+44 20 7946 0958',
    address: 'London, UK',
    productsSupplied: 4,
    totalOrders: 32,
    rating: 4.2,
    status: 'active',
  },
  {
    id: '4',
    name: 'LG Electronics',
    contactPerson: 'Kim Soo-yeon',
    email: 'sooyeon@lg.com',
    phone: '+82 2 3777 1114',
    address: 'Seoul, South Korea',
    productsSupplied: 1,
    totalOrders: 12,
    rating: 4.7,
    status: 'active',
  },
  {
    id: '5',
    name: 'Gaming Gear Inc.',
    contactPerson: 'Alex Rivera',
    email: 'alex@gaminggear.com',
    phone: '+1 (310) 555-0456',
    address: 'Los Angeles, CA, USA',
    productsSupplied: 2,
    totalOrders: 8,
    rating: 3.9,
    status: 'inactive',
  },
  {
    id: '6',
    name: 'Sony Corp.',
    contactPerson: 'Tanaka Hiroshi',
    email: 'hiroshi@sony.jp',
    phone: '+81 3 6748 2111',
    address: 'Tokyo, Japan',
    productsSupplied: 1,
    totalOrders: 15,
    rating: 4.9,
    status: 'active',
  },
  {
    id: '7',
    name: 'HP Inc.',
    contactPerson: 'Emily Brown',
    email: 'emily.brown@hp.com',
    phone: '+1 (650) 857-1501',
    address: 'Palo Alto, CA, USA',
    productsSupplied: 1,
    totalOrders: 10,
    rating: 4.4,
    status: 'active',
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: '1',
    action: 'product_created',
    entity: 'Product',
    entityId: '10',
    entityName: 'Printer LaserJet Pro',
    user: 'Admin',
    timestamp: '2024-01-20T14:30:00',
    details: 'New product added to inventory',
  },
  {
    id: '2',
    action: 'stock_updated',
    entity: 'Product',
    entityId: '7',
    entityName: 'Webcam HD 1080p',
    user: 'Admin',
    timestamp: '2024-01-20T13:15:00',
    details: 'Stock increased from 22 to 52 units (+30)',
  },
  {
    id: '3',
    action: 'transaction_created',
    entity: 'Transaction',
    entityId: '1',
    entityName: 'Sale - Laptop Dell XPS 15',
    user: 'John Doe',
    timestamp: '2024-01-20T10:30:00',
    details: 'Sale of 2 units to Acme Corp ($2,599.98)',
  },
  {
    id: '4',
    action: 'alert_triggered',
    entity: 'Alert',
    entityId: '1',
    entityName: 'Wireless Mouse Logitech',
    user: 'System',
    timestamp: '2024-01-20T08:00:00',
    details: 'Out-of-stock alert triggered (0 units)',
  },
  {
    id: '5',
    action: 'report_generated',
    entity: 'Report',
    entityId: 'rpt-001',
    entityName: 'Monthly Sales Report',
    user: 'Jane Smith',
    timestamp: '2024-01-19T17:00:00',
    details: 'PDF report generated for January 2024',
  },
  {
    id: '6',
    action: 'supplier_updated',
    entity: 'Supplier',
    entityId: '3',
    entityName: 'Tech Accessories Ltd.',
    user: 'Admin',
    timestamp: '2024-01-19T11:00:00',
    details: 'Updated contact information and rating',
  },
  {
    id: '7',
    action: 'ml_training',
    entity: 'ML Model',
    entityId: 'model-v3',
    entityName: 'Demand Forecasting v3',
    user: 'System',
    timestamp: '2024-01-19T03:00:00',
    details: 'Model retrained with latest 90-day data. Accuracy: 89.5%',
  },
  {
    id: '8',
    action: 'product_deleted',
    entity: 'Product',
    entityId: '11',
    entityName: 'Discontinued Cable Type-A',
    user: 'Admin',
    timestamp: '2024-01-18T16:00:00',
    details: 'Product removed from inventory (discontinued)',
  },
  {
    id: '9',
    action: 'alert_resolved',
    entity: 'Alert',
    entityId: '6',
    entityName: 'Office Chair Ergonomic',
    user: 'Admin',
    timestamp: '2024-01-18T14:00:00',
    details: 'Low-stock alert resolved after restocking',
  },
  {
    id: '10',
    action: 'user_login',
    entity: 'User',
    entityId: 'usr-001',
    entityName: 'John Doe',
    user: 'John Doe',
    timestamp: '2024-01-20T08:00:00',
    details: 'User logged in from 192.168.1.45',
  },
];

// Chart data for dashboard
export const salesChartData = [
  { name: 'Mon', sales: 4200, purchases: 2400 },
  { name: 'Tue', sales: 3800, purchases: 1398 },
  { name: 'Wed', sales: 5100, purchases: 3800 },
  { name: 'Thu', sales: 4780, purchases: 3908 },
  { name: 'Fri', sales: 5890, purchases: 4800 },
  { name: 'Sat', sales: 3390, purchases: 1800 },
  { name: 'Sun', sales: 2490, purchases: 1200 },
];

export const categoryDistribution = [
  { name: 'Electronics', value: 45, fill: 'hsl(217, 91%, 60%)' },
  { name: 'Accessories', value: 28, fill: 'hsl(270, 70%, 60%)' },
  { name: 'Furniture', value: 18, fill: 'hsl(142, 76%, 45%)' },
  { name: 'Office', value: 9, fill: 'hsl(38, 92%, 50%)' },
];

export const monthlyTrend = [
  { month: 'Jul', revenue: 18500, orders: 120 },
  { month: 'Aug', revenue: 22300, orders: 145 },
  { month: 'Sep', revenue: 19800, orders: 130 },
  { month: 'Oct', revenue: 25600, orders: 168 },
  { month: 'Nov', revenue: 31200, orders: 195 },
  { month: 'Dec', revenue: 28900, orders: 180 },
  { month: 'Jan', revenue: 34500, orders: 210 },
];

export const stockLevelData = mockProducts.map(p => ({
  name: p.name.split(' ').slice(0, 2).join(' '),
  current: p.quantity,
  threshold: p.minThreshold,
}));

export const demandForecastData = [
  { day: 'Week 1', actual: 120, predicted: 115 },
  { day: 'Week 2', actual: 135, predicted: 130 },
  { day: 'Week 3', actual: 128, predicted: 140 },
  { day: 'Week 4', actual: null, predicted: 155 },
  { day: 'Week 5', actual: null, predicted: 148 },
  { day: 'Week 6', actual: null, predicted: 162 },
];

export const mlAccuracyHistory = [
  { version: 'v1.0', accuracy: 72, date: 'Oct' },
  { version: 'v1.5', accuracy: 78, date: 'Nov' },
  { version: 'v2.0', accuracy: 83, date: 'Dec' },
  { version: 'v2.5', accuracy: 86, date: 'Jan' },
  { version: 'v3.0', accuracy: 89.5, date: 'Feb' },
];
