import { AlertTriangle, CheckCircle, XCircle, Clock } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { mockAlerts } from '@/lib/mockData';
import { toast } from 'sonner';

export default function Alerts() {
  const alerts = mockAlerts;
  const activeAlerts = alerts.filter(a => !a.resolved);

  const getSeverityColor = (severity: string) => {
    switch (severity) {
      case 'high':
        return 'destructive';
      case 'medium':
        return 'default';
      default:
        return 'secondary';
    }
  };

  const handleResolve = (id: string) => {
    toast.success('Alert resolved successfully');
    // Will be connected to C# backend API
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight flex items-center gap-2">
          <AlertTriangle className="h-8 w-8 text-warning" />
          Alerts & Notifications
        </h1>
        <p className="text-muted-foreground mt-1">
          Automatic alerts when stock levels fall below threshold
        </p>
      </div>

      <div className="grid gap-4 md:grid-cols-3">
        <Card className="shadow-soft">
          <CardHeader>
            <CardTitle className="text-sm font-medium">Active Alerts</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-destructive">{activeAlerts.length}</div>
            <p className="text-xs text-muted-foreground">Requires attention</p>
          </CardContent>
        </Card>

        <Card className="shadow-soft">
          <CardHeader>
            <CardTitle className="text-sm font-medium">High Priority</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-warning">
              {activeAlerts.filter(a => a.severity === 'high').length}
            </div>
            <p className="text-xs text-muted-foreground">Critical items</p>
          </CardContent>
        </Card>

        <Card className="shadow-soft">
          <CardHeader>
            <CardTitle className="text-sm font-medium">Resolved Today</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-success">
              {alerts.filter(a => a.resolved).length}
            </div>
            <p className="text-xs text-muted-foreground">Handled alerts</p>
          </CardContent>
        </Card>
      </div>

      <Card className="shadow-medium">
        <CardHeader>
          <CardTitle>Active Alerts</CardTitle>
          <CardDescription>
            Real-time notifications generated by the system
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          {activeAlerts.map((alert) => (
            <div
              key={alert.id}
              className="flex items-start gap-4 rounded-lg border p-4 hover:bg-muted/50 transition-colors"
            >
              <div className="mt-1">
                {alert.type === 'out-of-stock' ? (
                  <XCircle className="h-6 w-6 text-destructive" />
                ) : (
                  <AlertTriangle className="h-6 w-6 text-warning" />
                )}
              </div>

              <div className="flex-1 space-y-2">
                <div className="flex items-start justify-between">
                  <div>
                    <h3 className="font-semibold">{alert.productName}</h3>
                    <p className="text-sm text-muted-foreground mt-1">
                      {alert.message}
                    </p>
                  </div>
                  <Badge variant={getSeverityColor(alert.severity)}>
                    {alert.severity}
                  </Badge>
                </div>

                <div className="flex items-center gap-4 text-sm">
                  <div className="flex items-center gap-1">
                    <span className="font-medium">Current:</span>
                    <span className="text-destructive font-bold">
                      {alert.currentQuantity}
                    </span>
                  </div>
                  <div className="flex items-center gap-1">
                    <span className="font-medium">Threshold:</span>
                    <span>{alert.threshold}</span>
                  </div>
                  <div className="flex items-center gap-1 text-muted-foreground">
                    <Clock className="h-3 w-3" />
                    {new Date(alert.createdAt).toLocaleString()}
                  </div>
                </div>

                <div className="flex gap-2">
                  <Button
                    size="sm"
                    variant="default"
                    onClick={() => handleResolve(alert.id)}
                  >
                    <CheckCircle className="h-4 w-4 mr-1" />
                    Resolve
                  </Button>
                  <Button size="sm" variant="outline">
                    View Product
                  </Button>
                </div>
              </div>
            </div>
          ))}
        </CardContent>
      </Card>

      <Card className="shadow-medium border-primary/20">
        <CardHeader>
          <CardTitle>Alert System Features</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3 text-sm">
          <div className="flex items-start gap-2">
            <CheckCircle className="h-5 w-5 text-success mt-0.5" />
            <div>
              <p className="font-medium">Real-time Monitoring</p>
              <p className="text-muted-foreground">
                Automatic alerts via SignalR when stock falls below threshold
              </p>
            </div>
          </div>
          <div className="flex items-start gap-2">
            <CheckCircle className="h-5 w-5 text-success mt-0.5" />
            <div>
              <p className="font-medium">Priority Levels</p>
              <p className="text-muted-foreground">
                High, medium, and low severity classifications
              </p>
            </div>
          </div>
          <div className="flex items-start gap-2">
            <CheckCircle className="h-5 w-5 text-success mt-0.5" />
            <div>
              <p className="font-medium">Multi-user Notifications</p>
              <p className="text-muted-foreground">
                All connected users receive instant updates
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
